import json
import streamlit as st
from config import APP_CONFIG
from prompt_engine import build_prompt
from llm import generate_response_llm

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(
    page_title="AI Demo Suite",
    layout="wide"
)

# -------------------------------
# Select App (Foundation Switch)
# -------------------------------
app_name = st.sidebar.selectbox(
    "Select Demo",
    list(APP_CONFIG.keys())
)

config = APP_CONFIG[app_name]
# -------------------------------
# Fake Operational Metrics
# -------------------------------
st.sidebar.divider()

st.sidebar.subheader("Operations Overview")

st.sidebar.metric("Reports Generated", "148")
st.sidebar.metric("Critical Risks", "12")
st.sidebar.metric("Business Health", "72%")
st.sidebar.metric("Open Issues", "23")

# -------------------------------
# Header
# -------------------------------
st.title(config["title"])
st.info(config["use_case"])
st.write(config["description"])

# -------------------------------
# Mode Selector
# -------------------------------
mode = st.sidebar.selectbox(
    "Select Task",
    list(config["modes"].keys())
)

mode_config = config["modes"][mode]

# -------------------------------
# Session State Init
# -------------------------------
if "input_text_main" not in st.session_state:
    st.session_state.input_text_main = ""

if "output_text_main" not in st.session_state:
    st.session_state.output_text_main = ""

if "output_data_main" not in st.session_state:
    st.session_state.output_data_main = None
# -------------------------------
# Input Section
# -------------------------------
col_input, col_actions = st.columns([4, 1])

with col_input:
    user_input = st.text_area(
        "Enter your data:",
        value=st.session_state.input_text_main,
        height=260,
        placeholder=config.get("input_placeholder", "")
    )

with col_actions:
    st.write("")
    st.write("")

    if st.button("Load Example"):
        st.session_state.input_text_main = config["example_input"]
        st.rerun()

    if st.button("Clear"):
        st.session_state.input_text_main = ""
        st.session_state.output_text_main = ""
        st.rerun()
# -------------------------------
# Generate Button
# -------------------------------
generate_clicked = st.button("Generate", use_container_width=True)

# -------------------------------
# Processing
# -------------------------------
if generate_clicked:
    if not user_input.strip():
        st.warning("Please enter some input before generating.")
    else:
        template = mode_config["prompt"]
        

        prompt = build_prompt(template, user_input)

        with st.spinner("Analyzing..."):
            try:
                system_prompt = mode_config["system_prompt"]
        
                output = generate_response_llm(
                    prompt,
                    system_prompt
                )
        
                try:
                    parsed_output = json.loads(output)
        
                    st.session_state.output_text_main = output
                    st.session_state.output_data_main = parsed_output
        
                except json.JSONDecodeError:
                    st.error("Failed to parse AI response as JSON.")
        
                    st.session_state.output_text_main = output
                    st.session_state.output_data_main = None
        
            except Exception as e:
                st.error(f"Error: {str(e)}")
# -------------------------------
# Output Section
# -------------------------------
# -------------------------------
# Output Section
# -------------------------------
if st.session_state.output_data_main:

    data = st.session_state.output_data_main

    st.divider()

    st.subheader("Executive Business Report")
    col_meta1, col_meta2, col_meta3 = st.columns(3)

    with col_meta1:
        st.caption("Report ID: BR-2026-1042")
    
    with col_meta2:
        st.caption("Generated by AI Operations Engine")
    
    with col_meta3:
        st.caption("Processing Time: 1.8s")

    st.progress(92)

    st.caption("AI confidence score based on business pattern analysis.")

    # -------------------------------
    # Metrics Row
    # -------------------------------
    col1, col2 = st.columns(2)

    with col1:
        st.metric("Risk Level", data["risk_level"])

    with col2:
        st.metric("AI Confidence", "92%")

    # -------------------------------
    # Executive Summary
    # -------------------------------
    # -------------------------------
    # Workflow Tabs
    # -------------------------------
    tab1, tab2, tab3 = st.tabs([
        "Overview",
        "Findings",
        "Recommendations"
    ])
    
    # =====================================================
    # TAB 1 → OVERVIEW
    # =====================================================
    with tab1:
    
        st.subheader("Executive Summary")
    
        st.info(data["executive_summary"])
        # -------------------------------
        # Executive Alerts
        # -------------------------------
        st.subheader("Executive Alerts")
        
        st.error("Revenue decline exceeded quarterly threshold.")
        
        st.warning("Customer churn increased over the last 60 days.")
        
        st.info("Support ticket volume increased by 18%.")    
        st.subheader("Operational Status")
    
        if data["risk_level"] == "High":
            st.error("Business Risk Level: High")
    
        elif data["risk_level"] == "Medium":
            st.warning("Business Risk Level: Medium")
    
        else:
            st.success("Business Risk Level: Low")
    # -------------------------------
    # Recent System Activity
    # -------------------------------
    st.subheader("Recent System Activity")
    
    st.caption("09:41 AM • AI analyzed quarterly revenue trends")
    
    st.caption("09:43 AM • Customer churn anomaly detected")
    
    st.caption("09:44 AM • Operational risk score updated")
    
    st.caption("09:45 AM • Executive report generated")
    
    # =====================================================
    # TAB 2 → FINDINGS
    # =====================================================
    with tab2:
    
        st.subheader("Key Findings")
    
        for item in data["key_findings"]:
            st.write(f"• {item}")
    
        st.subheader("Problems Identified")
    
        for item in data["identified_problems"]:
            st.write(f"• {item}")
    
    # =====================================================
    # TAB 3 → RECOMMENDATIONS
    # =====================================================
    with tab3:
    
        st.subheader("Recommendations")
    
        for item in data["recommendations"]:
            st.write(f"• {item}")
    
        st.subheader("Business Outlook")
    
        st.warning(data["business_outlook"])

    st.warning(data["business_outlook"])# -------------------------------
# Footer (Subtle Branding)
# -------------------------------
st.divider()
st.caption("Demo: AI-powered workflow automation | Built with Streamlit + OpenAI")
