import json
import streamlit as st
from config import APP_CONFIG
from prompt_engine import build_prompt
from llm import generate_response_llm

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(
    page_title="AI Demo Suite",
    layout="wide"
)
# -------------------------------
# Global Enterprise Styling
# -------------------------------
st.markdown("""
<style>

/* Main App Background */
.main {
    background-color: #f5f7fb;
}

/* Card Containers */
.enterprise-card {
    background: white;
    padding: 20px;
    border-radius: 14px;
    border: 1px solid #e5e7eb;
    margin-bottom: 18px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04);
}

/* Section Headers */
.section-title {
    font-size: 20px;
    font-weight: 700;
    margin-bottom: 12px;
    color: #111827;
}

/* Small Metadata Text */
.meta-text {
    color: #6b7280;
    font-size: 13px;
}

/* KPI Metric Area */
.kpi-card {
    background: white;
    padding: 16px;
    border-radius: 12px;
    border: 1px solid #e5e7eb;
    text-align: center;
}

/* Reduce Excess Spacing */
.block-container {
    padding-top: 1.5rem;
    padding-bottom: 2rem;
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background-color: #ffffff;
    border-right: 1px solid #e5e7eb;
}

</style>
""", unsafe_allow_html=True)

# -------------------------------
# Select App (Foundation Switch)
# -------------------------------
app_name = st.sidebar.selectbox(
    "Select Demo",
    list(APP_CONFIG.keys())
)

config = APP_CONFIG[app_name]
# -------------------------------
# Fake Operational Metrics
# -------------------------------
st.sidebar.divider()

st.sidebar.subheader("Operations Overview")

st.sidebar.metric("Reports Generated", "148")
st.sidebar.metric("Critical Risks", "12")
st.sidebar.metric("Business Health", "72%")
st.sidebar.metric("Open Issues", "23")

# -------------------------------
# Header
# -------------------------------
st.title(config["title"])
st.info(config["use_case"])
st.write(config["description"])

# -------------------------------
# Mode Selector
# -------------------------------
mode = st.sidebar.selectbox(
    "Select Task",
    list(config["modes"].keys())
)

mode_config = config["modes"][mode]

# -------------------------------
# Session State Init
# -------------------------------
if "input_text_main" not in st.session_state:
    st.session_state.input_text_main = ""

if "output_text_main" not in st.session_state:
    st.session_state.output_text_main = ""

if "output_data_main" not in st.session_state:
    st.session_state.output_data_main = None
# -------------------------------
# Input Section
# -------------------------------

# -------------------------------
# Processing
# -------------------------------
# -------------------------------
# Output Section
# -------------------------------
# -------------------------------
# Output Section
# -------------------------------
if st.session_state.output_data_main:

    data = st.session_state.output_data_main

else:

    data = {
        "executive_summary":
            "AI operational monitoring dashboard ready for business analysis.",

        "risk_level": "Medium",

        "key_findings": [
            "Operational monitoring systems active",
            "Cross-department analysis ready",
            "AI workflow engine initialized"
        ],

        "identified_problems": [
            "Awaiting employee operational submissions"
        ],

        "recommendations": [
            "Continue operational monitoring",
            "Collect additional department updates"
        ],

        "business_outlook":
            "Business operations currently stable."
    }
st.divider()

st.subheader("Executive Business Report")
col_meta1, col_meta2, col_meta3 = st.columns(3)

with col_meta1:
    st.caption("Report ID: BR-2026-1042")

with col_meta2:
    st.caption("Generated by AI Operations Engine")

with col_meta3:
    st.caption("Processing Time: 1.8s")

st.progress(92)

st.caption("AI confidence score based on business pattern analysis.")

# -------------------------------
# Metrics Row
# -------------------------------
col1, col2 = st.columns(2)

with col1:

    st.markdown("""
    <div class="kpi-card">
        <div class="meta-text">Risk Level</div>
        <div style="font-size:32px;font-weight:700;color:#dc2626;">
            High
        </div>
    </div>
    """, unsafe_allow_html=True)

with col2:

    st.markdown("""
    <div class="kpi-card">
        <div class="meta-text">AI Confidence</div>
        <div style="font-size:32px;font-weight:700;color:#2563eb;">
            92%
        </div>
    </div>
    """, unsafe_allow_html=True)

# -------------------------------
# Executive Summary
# -------------------------------
# -------------------------------
# Workflow Tabs
# -------------------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "Employee Submission",
    "Executive Dashboard",
    "Operational Findings",
    "Recommendations"
])

# =====================================================
# TAB 1 → OVERVIEW
# =====================================================
with tab1:

    st.caption(
        "Employees submit operational updates for AI-driven business analysis and executive reporting."
    )

    col_input, col_actions = st.columns([4, 1])

    with col_input:

        # -------------------------------
        # Employee Metadata
        # -------------------------------
        meta_col1, meta_col2, meta_col3 = st.columns(3)

        with meta_col1:
            department = st.selectbox(
                "Department",
                ["Support", "Operations", "Sales", "Finance", "HR"]
            )

        with meta_col2:
            employee_priority = st.selectbox(
                "Priority Level",
                ["Low", "Medium", "High"]
            )

        with meta_col3:
            submitted_by = st.selectbox(
                "Submitted By",
                [
                    "Sarah - Support Lead",
                    "David - Operations Manager",
                    "Emily - Sales Team"
                ]
            )

        # -------------------------------
        # Operational Input
        # -------------------------------
        user_input = st.text_area(
            "Submit Operational Update:",
            key="input_text_main",
            height=260,
            placeholder=config.get("input_placeholder", "")
        )

    with col_actions:

        st.write("")
        st.write("")

        if st.button("Load Example"):
            st.session_state.input_text_main = config["example_input"]
            st.rerun()

        if st.button("Clear"):
            st.session_state.input_text_main = ""
            st.session_state.output_text_main = ""
            st.rerun()

    # -------------------------------
    # Submit Button
    # -------------------------------
    generate_clicked = st.button(
        "Submit Operational Report",
        use_container_width=True
    )
    if generate_clicked:
        if not user_input.strip():
            st.warning("Please enter some input before generating.")
        else:
            template = mode_config["prompt"]
            
    
            prompt = build_prompt(template, user_input)
    
            with st.spinner("Analyzing..."):
                try:
                    system_prompt = mode_config["system_prompt"]
            
                    output = generate_response_llm(
                        prompt,
                        system_prompt
                    )
            
                    try:
                        parsed_output = json.loads(output)
            
                        st.session_state.output_text_main = output
                        st.session_state.output_data_main = parsed_output
            
                    except json.JSONDecodeError:
                        st.error("Failed to parse AI response as JSON.")
            
                        st.session_state.output_text_main = output
                        st.session_state.output_data_main = None
            
                except Exception as e:
                    st.error(f"Error: {str(e)}")

# =====================================================
# TAB 2 → FINDINGS
# =====================================================
with tab2:

    st.caption(
        "AI-generated operational intelligence aggregated from cross-department employee submissions."
    )

    # =====================================================
    # TOP METRICS
    # =====================================================
    metric_col1, metric_col2, metric_col3, metric_col4 = st.columns(4)

    with metric_col1:
        st.metric("Departments Reporting", "5")

    with metric_col2:
        st.metric("Critical Alerts", "3")

    with metric_col3:
        st.metric("Operational Health", "72%")

    with metric_col4:
        st.metric("Active Issues", "12")

    st.divider()

    # =====================================================
    # MAIN DASHBOARD LAYOUT
    # =====================================================
    left_col, right_col = st.columns([2, 1])

    # =====================================================
    # LEFT SIDE
    # =====================================================
    with left_col:

        # -------------------------------
        # Executive Summary
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Executive Summary
            </div>
        """, unsafe_allow_html=True)

        st.info(data["executive_summary"])

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # Executive Alerts
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Executive Alerts
            </div>
        """, unsafe_allow_html=True)

        st.error("Refund complaints increased by 18% this week.")

        st.warning("Warehouse shipment delays detected across multiple regions.")

        st.info("Customer support response times increased during peak hours.")

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # Department Risk Overview
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Department Risk Overview
            </div>
        """, unsafe_allow_html=True)

        st.table({
            "Department": [
                "Support",
                "Operations",
                "Sales",
                "Finance",
                "HR"
            ],
            "Risk Level": [
                "High",
                "Medium",
                "Medium",
                "Low",
                "Low"
            ]
        })

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

    # =====================================================
    # RIGHT SIDE
    # =====================================================
    with right_col:

        # -------------------------------
        # Operational Status
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Operational Status
            </div>
        """, unsafe_allow_html=True)

        if data["risk_level"] == "High":
            st.error("Business Risk Level: High")

        elif data["risk_level"] == "Medium":
            st.warning("Business Risk Level: Medium")

        else:
            st.success("Business Risk Level: Low")

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # Recent System Activity
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Recent System Activity
            </div>
        """, unsafe_allow_html=True)

        st.caption("09:41 AM • Support department submitted escalation report")

        st.caption("09:43 AM • AI detected customer dissatisfaction trend")

        st.caption("09:44 AM • Operations risk score updated")

        st.caption("09:45 AM • Executive business report generated")

        st.caption("09:47 AM • Sales pricing concern flagged")

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # AI Confidence
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                AI Confidence Score
            </div>
        """, unsafe_allow_html=True)

        st.progress(92)

        st.caption(
            "Confidence score based on operational pattern analysis."
        )

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)
# =====================================================
# TAB 3 → RECOMMENDATIONS
# =====================================================
with tab3:

    st.subheader("Key Findings")

    for item in data["key_findings"]:
        st.write(f"• {item}")

    st.subheader("Problems Identified")

    for item in data["identified_problems"]:
        st.write(f"• {item}")
# =====================================================
# TAB 4 → RECOMMENDATIONS
# =====================================================
with tab4:

    st.subheader("Recommendations")

    for item in data["recommendations"]:
        st.write(f"• {item}")

    st.subheader("Business Outlook")

    st.warning(data["business_outlook"])
# -------------------------------
# Footer (Subtle Branding)
# -------------------------------
st.divider()
st.caption("Demo: AI-powered workflow automation | Built with Streamlit + OpenAI")
