import json
import streamlit as st
from config import APP_CONFIG
from prompt_engine import build_prompt
from llm import generate_response_llm

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(
    page_title="AI Factory Operations Intelligence",
    layout="wide"
)
# -------------------------------
# Global Enterprise Styling
# -------------------------------
st.markdown("""
<style>

/* Main App Background */
.main {
    background-color: #f5f7fb;
}

/* Card Containers */
.enterprise-card {
    background: white;
    padding: 20px;
    border-radius: 14px;
    border: 1px solid #e5e7eb;
    margin-bottom: 18px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04);
}

/* Section Headers */
.section-title {
    font-size: 20px;
    font-weight: 700;
    margin-bottom: 12px;
    color: #111827;
}

/* Small Metadata Text */
.meta-text {
    color: #6b7280;
    font-size: 13px;
}

/* KPI Metric Area */
.kpi-card {
    background: white;
    padding: 16px;
    border-radius: 12px;
    border: 1px solid #e5e7eb;
    text-align: center;
}

/* Reduce Excess Spacing */
.block-container {
    padding-top: 1.5rem;
    padding-bottom: 2rem;
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background-color: #ffffff;
    border-right: 1px solid #e5e7eb;
}

</style>
""", unsafe_allow_html=True)

# -------------------------------
# Select App (Foundation Switch)
# -------------------------------
config = APP_CONFIG["AI Factory Operations Intelligence"]


# -------------------------------
# Fake Operational Metrics
# -------------------------------
st.sidebar.divider()

st.sidebar.subheader("Operations Overview")

st.sidebar.metric("Reports Generated", "148")
st.sidebar.metric("Critical Risks", "12")
st.sidebar.metric("Business Health", "72%")
st.sidebar.metric("Open Issues", "23")

# -------------------------------
# Header
# -------------------------------
st.title(config["title"])
st.info(config["use_case"])
st.write(config["description"])

# -------------------------------
# Mode Selector
# -------------------------------
mode_config = config["mode"]

# -------------------------------
# Session State Init
# -------------------------------
if "input_text_main" not in st.session_state:
    st.session_state.input_text_main = ""

if "output_text_main" not in st.session_state:
    st.session_state.output_text_main = ""

if "output_data_main" not in st.session_state:
    st.session_state.output_data_main = None
# -------------------------------
# Input Section
# -------------------------------

# -------------------------------
# Processing
# -------------------------------
# -------------------------------
# Output Section
# -------------------------------
# -------------------------------
# Output Section
# -------------------------------
st.divider()

st.subheader("Executive Business Report")
col_meta1, col_meta2, col_meta3 = st.columns(3)

with col_meta1:
    st.caption("Report ID: BR-2026-1042")

with col_meta2:
    st.caption("Generated by AI Factory Intelligence Engine")

with col_meta3:
    st.caption("Processing Time: 1.8s")

st.progress(92)

st.caption("AI confidence score based on business pattern analysis.")

# -------------------------------
# Metrics Row
# -------------------------------
col1, col2 = st.columns(2)

with col1:

    st.markdown("""
    <div class="kpi-card">
        <div class="meta-text">Risk Level</div>
        <div style="font-size:32px;font-weight:700;color:#dc2626;">
            High
        </div>
    </div>
    """, unsafe_allow_html=True)

with col2:

    st.markdown("""
    <div class="kpi-card">
        <div class="meta-text">AI Confidence</div>
        <div style="font-size:32px;font-weight:700;color:#2563eb;">
            92%
        </div>
    </div>
    """, unsafe_allow_html=True)

# -------------------------------
# Executive Summary
# -------------------------------
# -------------------------------
# Workflow Tabs
# -------------------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "Factory Reports",
    "Operations Dashboard",
    "Production Intelligence",
    "Management Actions"
])

# =====================================================
# TAB 1 → OVERVIEW
# =====================================================
with tab1:

    st.caption(
        "Factory staff submit operational updates related to production, machine performance, quality control, and dispatch operations for AI-driven operational intelligence and management reporting."
    )

    col_input, col_actions = st.columns([4, 1])

    with col_input:

        # -------------------------------
        # Employee Metadata
        # -------------------------------
        meta_col1, meta_col2, meta_col3 = st.columns(3)

        with meta_col1:
            department = st.selectbox(
                "Department",
                [
                    "Production",
                    "Machine Maintenance",
                    "Quality Control",
                    "Inventory",
                    "Dispatch & Logistics",
                    "Client Coordination",
                    "Operations Management"
                ]
            )

        with meta_col2:
            employee_priority = st.selectbox(
                "Operational Priority",
                [
                    "Routine",
                    "Attention Needed",
                    "Urgent Production Risk",
                    "Critical Dispatch Risk"
                ]
            )

        with meta_col3:
            submitted_by = st.selectbox(
                "Submitted By",
                [
                    "Imran - Production Supervisor",
                    "Ahmed - Machine Technician",
                    "Bilal - QC Inspector",
                    "Faisal - Dispatch Coordinator",
                    "Usman - Inventory Manager"
                ]
            )

        # -------------------------------
        # Operational Input
        # -------------------------------
        if "input_text_main" not in st.session_state:
            st.session_state.input_text_main = ""
        
        user_input = st.text_area(
            "Submit Factory Operational Update:",
            value=st.session_state.input_text_main,
            key="factory_input_area",
            height=260,
            placeholder="""
        Example:
        Machine #12 experienced repeated thread tension failures during bulk embroidery runs.
        
        Production throughput dropped during the evening shift, and two export orders may miss dispatch deadlines if downtime continues.
        
        QC staff also reported increased stitching inconsistencies on premium garments requiring additional rework.
        """
        )
        st.session_state.input_text_main = user_input

    with col_actions:

        st.write("")
        st.write("")

        if st.button("Load Factory Scenario"):
            st.session_state.input_text_main = config["example_input"]
            st.rerun()

        if st.button("Clear"):
            st.session_state.input_text_main = ""
            st.session_state.output_text_main = ""
            st.rerun()

    # -------------------------------
    # Submit Button
    # -------------------------------
    generate_clicked = st.button(
        "Generate Operational Intelligence Report",
        use_container_width=True
    )

    if generate_clicked:

        if not user_input.strip():
    
            st.warning(
                "Please enter a factory operational update before continuing."
            )
    
        else:
    
            try:
    
                template = mode_config["prompt"]
    
                prompt = build_prompt(template, user_input)
    
                with st.spinner(
                    "Analyzing factory operations and generating executive insights..."
                ):
    
                    system_prompt = mode_config["system_prompt"]
    
                    output = generate_response_llm(
                        prompt,
                        system_prompt
                    )
    
                    parsed_output = json.loads(output)

                    st.session_state.output_text_main = output
                    st.session_state.output_data_main = parsed_output
                    
                    st.success("AI operational intelligence generated successfully.")
                    
                    st.write(parsed_output)
    
            except json.JSONDecodeError:
    
                st.error(
                    "Failed to parse AI operational intelligence response."
                )
    
            except Exception as e:
    
                st.error(f"Operational analysis error: {str(e)}")
if st.session_state.output_data_main:

    data = st.session_state.output_data_main

else:

    data = {
       "executive_summary":
            """
            Production efficiency declined this week due to recurring machine calibration issues and increased embroidery defects during peak production hours.
        
            Multiple export orders face dispatch delays, while quality control teams reported rising rework requirements on premium garments.
            """,

        "risk_level": "Medium",

        "key_findings": [
            "Machine downtime increased during evening production shifts",
            "Embroidery defect rates rose on premium export garments",
            "Dispatch delays affected 7 urgent client orders",
            "Fabric wastage increased due to stitching inconsistencies",
            "Production throughput dropped during peak workload periods"
        ],
        "identified_problems": [
            "Recurring machine calibration failures impacting production speed",
            "Increased rework requirements due to embroidery quality issues",
            "Thread inventory shortages delaying order completion",
            "Dispatch scheduling pressure affecting export timelines"
        ],

        "recommendations": [
            "Schedule preventive maintenance for high-usage embroidery machines",
            "Increase QC inspections during overtime production shifts",
            "Reallocate urgent export orders to available production lines",
            "Audit thread inventory forecasting process",
            "Monitor machine downtime trends across all production units"
        ],

        

        "business_outlook":
            """
            Operational pressure is increasing across production and dispatch workflows. 
            Immediate maintenance intervention and production optimization are recommended 
            to reduce export delays, minimize rework costs, and stabilize factory throughput.
            """
    }

# =====================================================
# TAB 2 → FINDINGS
# =====================================================
with tab2:

    st.caption(
        "AI-generated operational intelligence aggregated from cross-department employee submissions."
    )

    # =====================================================
    # TOP METRICS
    # =====================================================
    # =====================================================
    # TOP METRICS ROW 1
    # =====================================================
    metric_col1, metric_col2, metric_col3, metric_col4 = st.columns(4)
    
    with metric_col1:
        st.metric("Departments Reporting", "5")
    
    with metric_col2:
        st.metric("Critical Alerts", "3")
    
    with metric_col3:
        st.metric("Operational Health", "72%")
    
    with metric_col4:
        st.metric("Active Issues", "12")
    
    # =====================================================
    # TOP METRICS ROW 2
    # =====================================================
    # =====================================================
    # TOP METRICS ROW 2
    # =====================================================
    metric_col5, metric_col6, metric_col7 = st.columns(3)
    
    with metric_col5:
        st.metric("Revenue Impact", "$48K")
    
    with metric_col6:
        st.metric("Production Delays", "7 Orders")
    
    with metric_col7:
        st.metric("Machine Downtime", "14 hrs")
    
    # =====================================================
    # TOP METRICS ROW 3
    # =====================================================
    metric_col8, metric_col9, metric_col10, metric_col11 = st.columns(4)
    
    with metric_col8:
        st.metric("Machines Active", "18/24")
    
    with metric_col9:
        st.metric("Machines Under Maintenance", "3")
    
    with metric_col10:
        st.metric("Production Efficiency", "72%")
    
    with metric_col11:
        st.metric("Daily Output Completion", "81%")
    
    st.divider()
    # =====================================================
    # MAIN DASHBOARD LAYOUT
    # =====================================================
    left_col, right_col = st.columns([2, 1])

    # =====================================================
    # LEFT SIDE
    # =====================================================
    with left_col:

        # -------------------------------
        # Executive Summary
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Executive Summary
            </div>
        """, unsafe_allow_html=True)

        st.info(
            data.get(
                "executive_summary",
                data.get(
                    "overall_operational_summary",
                    "No executive summary generated."
                )
            )
        )

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # Executive Alerts
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Executive Alerts
            </div>
        """, unsafe_allow_html=True)

        st.error("Machine downtime increased during peak embroidery production hours.")
        
        st.warning("Urgent export orders face dispatch delay risk.")
        
        st.info("QC teams detected rising stitching inconsistencies on premium garments.")

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # Department Risk Overview
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Department Risk Overview
            </div>
        """, unsafe_allow_html=True)

        st.table({
            "Department": [
                "Production",
                "Machine Maintenance",
                "Quality Control",
                "Inventory",
                "Dispatch & Logistics"
            ],
            "Risk Level": [
                "High",
                "Medium",
                "High",
                "Medium",
                "Critical"
            ]
        })

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

    # =====================================================
    # RIGHT SIDE
    # =====================================================
    with right_col:

        # -------------------------------
        # Operational Status
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Production Risk Status
            </div>
        """, unsafe_allow_html=True)

        risk_level = data.get("risk_level", "Medium")

        if risk_level == "High":
            st.error("Production Risk Level: High")
        
        elif risk_level == "Medium":
            st.warning("Production Risk Level: Medium")
        
        else:
            st.success("Production Risk Level: Low")

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # Recent System Activity
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                Recent System Activity
            </div>
        """, unsafe_allow_html=True)

        st.caption("09:41 AM • Production supervisor reported machine downtime")

        st.caption("09:43 AM • AI detected increased dispatch risk")
        
        st.caption("09:44 AM • QC defect trend identified")
        
        st.caption("09:45 AM • Factory operations report generated")
        
        st.caption("09:47 AM • Inventory shortage alert triggered")

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)

        # -------------------------------
        # AI Confidence
        # -------------------------------
        st.markdown("""
        <div class="enterprise-card">
            <div class="section-title">
                AI Confidence Score
            </div>
        """, unsafe_allow_html=True)

        st.progress(92)

        st.caption(
            "Confidence score based on operational pattern analysis."
        )

        st.markdown("""
        </div>
        """, unsafe_allow_html=True)
# =====================================================
# TAB 3 → RECOMMENDATIONS
# =====================================================
with tab3:

    st.subheader("Key Findings")

    for item in data.get("key_findings", []):
        st.write(f"• {item}")

    st.subheader("Problems Identified")

    for item in data.get("identified_problems", []):
        st.write(f"• {item}")
# =====================================================
# TAB 4 → RECOMMENDATIONS
# =====================================================
with tab4:

    st.subheader("Recommendations")

    for item in data.get("recommendations", []):
        st.write(f"• {item}")

    st.subheader("Business Outlook")

    st.warning(
        data.get(
            "business_outlook",
            "No operational outlook generated."
        )
    )
# -------------------------------
# Footer (Subtle Branding)
# -------------------------------
st.divider()
st.caption("Demo: AI-powered factory operations intelligence | Built with Streamlit + OpenAI")
